config/routes.rb
Rails.application.routes.draw do

  root 'construction#index'
  post '/construction', to: 'construction#email', as: 'add_email'

  resources :brokers
  get '/home', to: 'welcome#index'
  post 'sms/received', to: 'sms#received', as: 'received'
  get 'leads/:response_url', to: 'leads#show', as: 'respond_to_lead'

  get 'leads/:resonse_url/thank-you', to: 'leads#thank_you', as:'thank_you'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'

  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/authenticate', to: 'sessions#authenticate_broker', as: 'authenticate_broker'
  post '/authenticate', to: 'sessions#check_broker'

  post '/authorize', to: 'sessions#authorize_broker'

  get '/appointments/:availability_url/', to: 'appointments#show', as: 'schedule_appointment'
  get '/appointments/:availability_url/thank-you', to: 'appointments#thank_you', as: 'appointment_submitted'
  
  patch '/appointments/:availability_url', to: 'appointments#update', as: 'appointment'

  post '/properties/', to: 'properties#create', as: 'new_property'
  post '/properties/previous', to: 'properties#previous', as: 'previous_properties'

  get '/appointments/:user_cal_url/user', to: 'appointments#add_user_cal', as: 'user_calendar'
  get '/appointments/:broker_cal_url/broker', to: 'appointments#add_broker_cal', as: 'broker_calendar'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :properties
  has_many :appointments

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :redirect_broker

  def show
    @lead = Lead.find_by_response_url(params[:response_url])
    @broker = Broker.find(cookies[:broker_id])
    @property = Property.new
    if @lead.user.is_inactive?
      flash[:error] = "TENANT IS NO LONGER ACTIVE"
    end
  end

  def thank_you
    @response_url = params[:resonse_url]
    render :thank_you
  end
end

app/helpers/leads_helper.rb
module LeadsHelper

  def lead_complete?(number)
    user = User.find_by_phone_number(number)
    return user.leads.last.complete
  end

  def image(property)
    @file = property.image_url.load.files[0].cdn_url
    return @file
  end


end

app/views/leads/_form.html.erb
<%= form_for @property, url: '/properties/', method: 'post', validate: true do |f| %>
  <fieldset>
    <legend>Property</legend>
    <div class="row">
      <div class="medium-6 columns">
        <%= f.label "Property Address*" %>
        <%= f.text_field :address, required: true, class: "prop-form", placeholder: "Ex: '300 Bush St'" %>
      </div>
      <div class="medium-6 columns">
        <%= f.label "Sub-Market*" %>
        <%= f.select :sub_market, options_for_select([["North Financial"], ["South Financial"], ["SOMA"], ["Mid-Market"], ["Jackson Square"], ["Showplace Square"], [
          "Mission"], ["Potrero"], ["Union Square"], ["North Waterfront"], ["Yerba Buena"]]), { prompt: "Select Sub Market"}, {required: 'true', class: "prop-form"}%>
      </div>
    </div>
    <div class="row">
      <div class="medium-6 columns">
        <%= f.label "Property Type*" %>
        <%= f.select :property_type, options_for_select([["Creative", "creative"], ["Traditional", "traditional"]]), {prompt: "Select type of type of space"}, {required: 'true', class: "prop-form"}%>
      </div>

      <div class="medium-5 small-10 columns sqft">
        <%= f.label "Square Feet - enter just the number*" %>
        <%= f.telephone_field :sq_ft, required: true, class: "prop-form", placeholder: "Ex: 1200" %>
      </div>
      <div class="medium-1 small-2 columns sqft">
        <span class="postfix sqft">sq ft</span>
      </div>
    </div>
    <div class="row">
      <div class="medium-1 small-2 columns price">
        <span class="prefix price">$</span>
      </div>
      <div class="medium-5 small-10 columns price">
        <%= f.label "Price Per Sq Ft/yr*" %>
        <%= f.telephone_field :rent_price, required: true, class: "prop-form", placeholder: "Ex: 65" %>
      </div>
      <div class="medium-6 columns">
        <%= f.label "Available Date*" %>
        <%= f.date_field :available, class: "date prop-form", value: Date.today.to_s %>
      </div>
    </div>
    <div class="row">
      <div class="medium-6 small-12 columns sqft">
        <%= f.label "Minumum Lease Term (months)" %>
        <%= f.telephone_field :min, class: "prop-form", placeholder: "Ex: '12'" %>
      </div>
      <div class="medium-6 small-12 columns sqft">
        <%= f.label "Maximum Lease Term (months)" %>
        <%= f.telephone_field :max, class: "prop-form", placeholder: "Ex: '24'" %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 small-centered columns">
        <%= f.label :description %>
        <%= f.text_area :description, class: "prop-form", placeholder: "Enter a basic description for the tenant" %>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label "Add an image" %>
        <%= f.uploadcare_multiple_uploader_field :image_url %>
        <p class="legal">Image file formats only (jpg, jpeg, png, gif, or pdf)<br><span class="ital">Tip: you can select and include multiple files</span><br>*Photos, flyers, & floor plans only, and must be your own.</p>
      </div>
    </div><br>
    
    <%= f.hidden_field :lead_id, :value => @lead.id %>
    <%= f.hidden_field :broker_id, :value => @broker.id %>
    
    <div class="row">
      <div class="small-12 small-centered columns">
        <div class="test">
          <%= f.submit "Submit", class: "button cust-btn"%>
          <%= render 'layouts/spinner' %>
        </div>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/leads/_previous_properties.html.erb
<%= form_tag previous_properties_path, method: 'post', class: "custom" do %>
  <fieldset>
    <p>Click 1 or more properties below to send your selections to the tenant.</p>
    <legend>Previous Properties</legend>
    <% @broker.properties.order(created_at: :desc).each do |prop| %>
      <label for=<%= prop.id %>>
        <div class='panel cust-panel'>
          <div class='row'>
            <div class="small-1 columns">
              <%= check_box_tag 'property_ids[]', prop.id, nil, :id => prop.id %>
            </div>
            <span class="custom checkbox"></span>
            <div class="small-3 columns">
              <% if prop.image_url? %>
                <%= image_tag(image prop) %>
              <% else %>
                No Image :(
              <% end %>
            </div>
            <div class="small-4 columns">
              <strong>Address:</strong> <%= prop.address %><br>
              <strong>Sq Ft:</strong> <%= prop.sq_ft %><br>
              <strong>Added:</strong> <%= time_ago_in_words(prop.created_at) + " ago " %><i class="fi-clock"></i>
            </div>
            <div class="small-4 columns">
              <strong>Description:</strong> <%= prop.description %>
            </div>
          </div>
        </div>
      </label>
    <% end %>

    <%= hidden_field_tag :lead_id, @lead.id %>
    
    <div class="test">
      <%= submit_tag 'Submit', class: "button cust-btn prevSub", disabled: true  %>
      <%= render 'layouts/spinner' %>
    </div>

  </fieldset>
<% end %>
  

app/views/leads/show.html.erb
<% if @lead.user.is_inactive? %>
  <div class="row">
    <div class="small-12 large-10 large-centered columns">
      <p class="">This user has unsubscribed from James, and is no longer receiving SMS messages. If you submit a property using the form below, the user will only receive this info if they choose to re-subscribe</p>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="small-12 large-10 large-centered columns">
    <div class="lead-header" id="lead-response">
    	<h1 class="lead-header top">Respond to Lead</h1>
      <p><strong>Tenant Name:</strong> <%= @lead.user.name %>, <strong>Desired Market:</strong> <%= @lead.q_one %>, <strong># of people:</strong> <%= @lead.q_two %>, <strong>Vibe:</strong> <%= @lead.q_three %>, <strong>Date:</strong> <%= @lead.q_four %>, <strong>Term length:</strong> <%= @lead.q_five%>, <strong>Notes:</strong> <%= @lead.q_six %></p>
    	<%= render 'form' %>
      <% if @broker.properties != [] %>
        <%= render 'previous_properties' %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $('input[type=checkbox]').on('click', function(e){
      var $boxes = $('input[type=checkbox]');
    if (checkForCheck($boxes)){
      $('.prevSub').removeAttr('disabled');
    } else {
      $('.prevSub').attr('disabled','disabled');
    };
  });

  $('form').on('submit', function(){
    $(this).find('input[type=submit]').attr('disabled', 'disabled');
    $(this).find('.spinner').css('display', 'block');
  });

  var checkForCheck = function(boxes){
    var numBoxes = boxes.length
    for (var i=0; i < numBoxes; i++){
      if(boxes[i].checked){
        return true;
      }
    }
    return false;
  }
</script>

app/views/leads/thank_you.html.erb
<div class="row thanks">
  <div class="large-6 large-centered small-12 small-centered columns">
    <h1 class="broker-check top">Thank you!</h1>
    <p class="broker-check">You’ll hear back from me shortly if there’s a match.</p>
    </p>
    <div class="row">
      <div class="medium-6 medium-centered small-12 small-centered columns">
        <%= link_to("Submit another!", respond_to_lead_path(@response_url), class: "button cust-btn") %>
      </div>
    </div>
  </div>
</div>