config/routes.rb
Rails.application.routes.draw do

  root 'construction#index'
  post '/construction', to: 'construction#email', as: 'add_email'

  resources :brokers
  get '/home', to: 'welcome#index'
  post 'sms/received', to: 'sms#received', as: 'received'
  get 'leads/:response_url', to: 'leads#show', as: 'respond_to_lead'

  get 'leads/:resonse_url/thank-you', to: 'leads#thank_you', as:'thank_you'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'

  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/authenticate', to: 'sessions#authenticate_broker', as: 'authenticate_broker'
  post '/authenticate', to: 'sessions#check_broker'

  post '/authorize', to: 'sessions#authorize_broker'

  get '/appointments/:availability_url/', to: 'appointments#show', as: 'schedule_appointment'
  get '/appointments/:availability_url/thank-you', to: 'appointments#thank_you', as: 'appointment_submitted'
  
  patch '/appointments/:availability_url', to: 'appointments#update', as: 'appointment'

  post '/properties/', to: 'properties#create', as: 'new_property'
  post '/properties/previous', to: 'properties#previous', as: 'previous_properties'

  get '/appointments/:user_cal_url/user', to: 'appointments#add_user_cal', as: 'user_calendar'
  get '/appointments/:broker_cal_url/broker', to: 'appointments#add_broker_cal', as: 'broker_calendar'
end

app/models/broker.rb
class Broker < ActiveRecord::Base
  has_many :properties
  validates :email, uniqueness: true
  validates :first_name, :last_name, :email, :phone_number, presence: true

  @@client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']

  def create_sms_msg(to, body)
    @@client.messages.create({
        from: '+14158010226',
        to: to,
        body: body
      })
  end

  def self.is_broker?(number)
    @broker = Broker.find_by_phone_number(number)
    return @broker unless @broker == nil
  end

  def set_auth_code
    auth_code = rand(10000)
    update_column(:auth_code, auth_code)
    auth_message = "Your authorization code is #{auth_code}"
    create_sms_msg(phone_number, auth_message)
  end

  def self.resubmit_lead(lead)
    bitly = Bitly.client.shorten("https://www.textjames.co/leads/#{lead.response_url}")
    lead_msg = "Response requested for a previously submitted lead. #{lead.q_one}, #{lead.q_two} people, Term length: #{lead.q_five}, Notes: #{lead.q_six}, Click here to respond #{bitly.short_url}"
    self.all.each { |broker| broker.create_sms_msg(broker.phone_number, lead_msg) }
  end

end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController
  before_action :redirect_unauthenticated

  def index
    @brokers = Broker.all
  end

  def new
    @broker = Broker.new
  end

  def create
    @broker = Broker.new(broker_params)
    if @broker.save
      flash[:success] = 'Broker was successfully added.'
      redirect_to brokers_path
    else
      flash[:error] = "#{@broker.errors.each { |e| e }}"
      redirect_to new_broker_path
    end
  end

  def edit
    @broker = Broker.find(params[:id])
  end

  def destroy
    @broker = Broker.find(params[:id])
    @broker.destroy
    flash[:success] = 'Broker was succesfully deleted'
    redirect_to brokers_path
  end

  private

  def broker_params
    params.require(:broker).permit(:first_name, 
                                    :last_name, 
                                    :email, 
                                    :company, 
                                    :phone_number)
  end
end

app/helpers/brokers_helper.rb
module BrokersHelper
  @@client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']

  def send_lead(to, body)
    @@client.messages.create({
      :from => '+14158010226', 
      :to => to, 
      :body => body
      })
  end

  def trigger_lead(lead)
    @brokers = Broker.all
    bitly = Bitly.client.shorten("https://www.textjames.co/leads/#{lead.response_url}")
    message = "New lead - Tenant: #{lead.user.name}, #{lead.q_one}, #{lead.q_two} ppl, #{lead.q_three}, #{lead.q_four}, Term length: #{lead.q_five}. Notes: #{lead.q_six}, Click here to respond #{bitly.short_url}"
    @brokers.each { |broker| send_lead(broker.phone_number, message) }
  end
end

app/views/brokers/_form.html.erb
<%= form_for @broker, url: '/brokers', method: 'post' do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "prop-form" %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "prop-form" %><br>

  <%= f.label :email %>
  <%= f.text_field :email, class: "prop-form" %><br>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class: "prop-form" %><br>

  <%= f.label :company %>
  <%= f.text_field :company, class: "prop-form" %><br>


  <div class="actions">
    <%= f.submit class: "button cust-btn" %>
  </div>
<% end %>

app/views/brokers/create.html.erb
<h1>Brokers#create</h1>
<p>Find me in app/views/brokers/create.html.erb</p>

app/views/brokers/edit.html.erb
<h1 class="top">Edit Broker Profile for <%= @broker.first_name %></h1>
<%= render 'form' %>

app/views/brokers/index.html.erb
<h1>Brokers page</h1>

<table>
  <thead>
    <tr>
      <th width="200">Name</th>
      <th>Email</th>
      <th width="150">Number</th>
      <th width="150">Company</th>
      <th width="150">Date added</th>
      <th width="150">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @brokers.each do |broker| %>
      <tr>
        <td><%= broker.first_name %> <%= broker.last_name %></td>
        <td><%= broker.email %></td>
        <td><%= broker.phone_number %></td>
        <td><%= broker.company %></td>
        <td><%= broker.created_at %></td>
        <td><%= link_to "Edit", edit_broker_path(broker) %> | <%= link_to 'Delete', broker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/brokers/new.html.erb
<div class="row">
  <div class="medium-6 medium-centered columns">
    <h1 class="broker-check top">Add Broker</h1>
    <%= render 'form' %>
  </div>
</div>