config/routes.rb
Rails.application.routes.draw do

  root 'construction#index'
  post '/construction', to: 'construction#email', as: 'add_email'

  resources :brokers
  get '/home', to: 'welcome#index'
  post 'sms/received', to: 'sms#received', as: 'received'
  get 'leads/:response_url', to: 'leads#show', as: 'respond_to_lead'

  get 'leads/:resonse_url/thank-you', to: 'leads#thank_you', as:'thank_you'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'

  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/authenticate', to: 'sessions#authenticate_broker', as: 'authenticate_broker'
  post '/authenticate', to: 'sessions#check_broker'

  post '/authorize', to: 'sessions#authorize_broker'

  get '/appointments/:availability_url/', to: 'appointments#show', as: 'schedule_appointment'
  get '/appointments/:availability_url/thank-you', to: 'appointments#thank_you', as: 'appointment_submitted'
  
  patch '/appointments/:availability_url', to: 'appointments#update', as: 'appointment'

  post '/properties/', to: 'properties#create', as: 'new_property'
  post '/properties/previous', to: 'properties#previous', as: 'previous_properties'

  get '/appointments/:user_cal_url/user', to: 'appointments#add_user_cal', as: 'user_calendar'
  get '/appointments/:broker_cal_url/broker', to: 'appointments#add_broker_cal', as: 'broker_calendar'
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <footer >
    <div class="row">
      <div class="small-12 large-6 large-centered columns">       
        <div id="social-links">
          <a href="https://www.facebook.com/textjamesco"><i class="fi-social-facebook social"></i></a>
          <a href="https://twitter.com/Textjamesco"><i class="fi-social-twitter social"></i></a>
        </div>
        <div>
          <p class="footer-txt">
            Made in San Francisco | © 2015 Text James Co.
          </p>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Admin Home", admin_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="has-dropdown">
            <a href="#">Hi, <%= current_admin.broker.first_name %></a>
            <ul class="dropdown">
              <li><%= link_to 'Brokers', brokers_path %></li>
              <li><%= link_to 'Add Broker', new_broker_path %></li>
              <li class="active"><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        </ul>
        <!-- Left Nav Section -->
      </section>

    </nav>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<div class="row">
  <div class="small-12 small-centered columns">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_spinner.html.erb
<div class="spinner">
  <div class="double-bounce1"><%= image_tag('james_logo_sm.png') %></div>
  <div class="double-bounce2"><%= image_tag('james_logo_sm.png') %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Text James | Commercial Real Estate Concierge" %></title>
    <%= javascript_include_tag "//cdn.optimizely.com/js/3539122536.js" %>
    <%= favicon_link_tag 'james_logo.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= include_uploadcare_widget_from_cdn version: "1.5.5", min: true %>
    <%= uploadcare_settings %>
    <script type="text/javascript" src="https://addthisevent.com/libs/1.6.0/ate.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>